In [1]:
import pandas as pd

CSV_DIR = "test.csv"

In [5]:
df = pd.read_csv(CSV_DIR)
df.head()

,in_dims,hid_dims,ks,skips,gyrations,use_weight,norms,use_writer,iterations,epochs,lrs,no_fd_mean,no_fd_std,fd_mean,fd_std
0,100,25,3,0,True,True,1.0,False,30,20,0.00100,0.065581,0.039695,0.071168,0.032939
1,100,25,3,0,True,True,1.0,False,30,20,0.00050,0.262575,0.088598,0.276740,0.080725
2,100,25,3,0,True,True,1.0,False,30,20,0.00010,0.576092,0.115445,0.574216,0.100220
3,100,25,3,0,True,True,1.0,False,30,20,0.00005,0.634294,0.123689,0.649610,0.121254
4,100,25,3,0,True,True,2.0,False,30,20,0.00100,0.065373,0.031286,0.072188,0.030145

In [31]:
# plot df according to in_dims
import matplotlib.pyplot as plt
import numpy as np

col = 'lrs'

df[[col, 'fd_mean', 'fd_std', 'no_fd_mean', 'no_fd_std']].groupby(col).agg([np.mean, np.std])

          fd_mean              fd_std           no_fd_mean            \
             mean       std      mean       std       mean       std
lrs
0.00005  0.311460  0.255818  0.064342  0.043794   0.311908  0.256656
0.00010  0.231690  0.242568  0.052404  0.042848   0.231288  0.242058
0.00050  0.062520  0.094142  0.023430  0.034296   0.062093  0.093613
0.00100  0.012758  0.023407  0.007472  0.014538   0.012604  0.022971

        no_fd_std
             mean       std
lrs
0.00005  0.064452  0.044335
0.00010  0.051042  0.041626
0.00050  0.022286  0.032774
0.00100  0.006954  0.013263