In [1]:
import pandas as pd

CSV_DIR = "../results/scores.csv"
df = pd.read_csv(CSV_DIR)
df.head()

,name,no_fd_loss_mean_train,no_fd_acc_mean_train,no_fd_f1_mean_train,no_fd_loss_mean_val,no_fd_acc_mean_val,no_fd_f1_mean_val,no_fd_loss_std_train,no_fd_acc_std_train,no_fd_f1_std_train,...,k,skip,gyration,use_weight,norm,use_writer,iterations,epochs,lr,use_fd
0,citeseer,0.144575,0.930761,0.924169,0.030515,0.9976,0.995796,0.010719,0.004994,0.005133,...,5,1,True,True,1,False,10,40,0.005,False
1,cora,0.083222,0.974503,0.971322,0.027594,0.9958,0.995069,0.014038,0.003826,0.004119,...,5,1,True,True,1,False,10,40,0.005,False
2,facebook,0.190944,0.936062,0.930761,0.086736,0.9758,0.973445,0.013754,0.004911,0.005378,...,5,1,True,True,1,False,10,40,0.005,False

In [15]:
metric = 'f1'
cols = [any(items in col for items in ['name', metric, 'p_value', 't_test']) for col in df.columns]
df.iloc[:, cols]

,name,no_fd_f1_mean_train,no_fd_f1_mean_val,no_fd_f1_std_train,no_fd_f1_std_val,fd_f1_mean_train,fd_f1_mean_val,fd_f1_std_train,fd_f1_std_val,t_test,p_value
0,citeseer,0.924169,0.995796,0.005133,0.000705,0.934112,0.995949,0.006683,0.000610,5.125003,7.090000e-05
1,cora,0.971322,0.995069,0.004119,0.002956,0.984042,0.997450,0.002520,0.002125,8.379176,1.260000e-07
2,facebook,0.930761,0.973445,0.005378,0.004626,0.932097,0.975422,0.006514,0.006374,0.004756,9.962572e-01