In [21]:
import pandas as pd

CSV_DIR = "../results/scores.csv"
df = pd.read_csv(CSV_DIR)
df.head()

,name,no_fd_loss_mean_train,no_fd_acc_mean_train,no_fd_f1_mean_train,no_fd_loss_mean_val,no_fd_acc_mean_val,no_fd_f1_mean_val,no_fd_loss_std_train,no_fd_acc_std_train,no_fd_f1_std_train,...,k,skip,gyration,use_weight,norm,use_writer,iterations,epochs,lr,use_fd
0,cora,0.584301,0.796645,0.737909,0.485642,0.841053,0.780536,0.606322,0.245679,0.315171,...,4,0,True,True,1,True,10,30,0.005,False
1,citeseer,0.442576,0.845021,0.803621,0.363236,0.880845,0.838962,0.571931,0.230487,0.294231,...,4,0,True,True,1,True,10,40,0.005,False
2,facebook,0.338018,0.879081,0.860976,0.274632,0.906185,0.889864,0.296577,0.130648,0.157834,...,4,0,True,True,1,True,10,40,0.005,False

In [35]:
metric = 'loss'
cols = [any(items in col for items in ['name', metric, 'p_value', 't_test']) for col in df.columns]
df.iloc[:, cols]

,name,no_fd_loss_mean_train,no_fd_loss_mean_val,no_fd_loss_std_train,no_fd_loss_std_val,fd_loss_mean_train,fd_loss_mean_val,fd_loss_std_train,fd_loss_std_val,t_test,p_value
0,cora,0.584301,0.485642,0.606322,0.598889,0.485137,0.394359,0.586648,0.569403,4.851676,0.000128
1,citeseer,0.442576,0.363236,0.571931,0.551417,0.375139,0.303727,0.552571,0.529326,5.905590,0.000014
2,facebook,0.338018,0.274632,0.296577,0.290976,0.336534,0.275454,0.298283,0.292362,1.135647,0.271000